### ISSUE TITLE
Reserved RSQL keywords causes RSQLParserException

### ISSUE THREAD

**Issue by derylspielman** [perplexhub/rsql-jpa-specification#101]
I'm trying to do a simple search on an entity where name is like `RSQL's`. Because apostraphe, comma, parenthesis, etc. are reserved keywords in RSQL it's causing below exception. I believe we need to implement proper escaping of these keywords.

```java
@Test
void findAll_RsqlSpecificationIncludingApostraphe_ClientFoundInsteadOfException() {

    List<Client> expected = List.of(clientCRsql);

    String query = "name=ilike=RSQL's";
    List<Client> actual = clientRepository.findAll(RSQLJPASupport.toSpecification(query, false));

    assertEquals(expected, actual);
}
```

```java
cz.jirutka.rsql.parser.RSQLParserException: cz.jirutka.rsql.parser.TokenMgrError: Lexical error at line 1, column 17.  Encountered: [EOF] after : "\'s"
 at cz.jirutka.rsql.parser.RSQLParser.parse([RSQLParser.java:123](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.RSQLParser.parse(RSQLParser.java%3A123)%22%2C%22example-app%22%5D))
 at io.github.perplexhub.rsql.RSQLJPASupport.lambda$toSpecification$7eef092d$1([RSQLJPASupport.java:119](command:_java.test.openStackTrace?%5B%22%5Ctat%20io.github.perplexhub.rsql.RSQLJPASupport.lambda%24toSpecification%247eef092d%241(RSQLJPASupport.java%3A119)%22%2C%22example-app%22%5D))
 at org.springframework.data.jpa.repository.support.SimpleJpaRepository.applySpecificationToCriteria([SimpleJpaRepository.java:810](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.SimpleJpaRepository.applySpecificationToCriteria(SimpleJpaRepository.java%3A810)%22%2C%22example-app%22%5D))
 at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery([SimpleJpaRepository.java:744](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java%3A744)%22%2C%22example-app%22%5D))
 at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery([SimpleJpaRepository.java:729](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java%3A729)%22%2C%22example-app%22%5D))
 at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll([SimpleJpaRepository.java:466](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java%3A466)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0([RepositoryMethodInvoker.java:288](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryMethodInvoker%24RepositoryFragmentMethodInvoker.lambda%24new%240(RepositoryMethodInvoker.java%3A288)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke([RepositoryMethodInvoker.java:136](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java%3A136)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke([RepositoryMethodInvoker.java:120](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java%3A120)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke([RepositoryComposition.java:516](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryComposition%24RepositoryFragments.invoke(RepositoryComposition.java%3A516)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryComposition.invoke([RepositoryComposition.java:285](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java%3A285)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke([RepositoryFactorySupport.java:628](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryFactorySupport%24ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java%3A628)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke([QueryExecutorMethodInterceptor.java:168](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java%3A168)%22%2C%22example-app%22%5D))
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke([QueryExecutorMethodInterceptor.java:143](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java%3A143)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke([DefaultMethodInvokingMethodInterceptor.java:77](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java%3A77)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation([TransactionInterceptor.java:123](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionInterceptor%241.proceedWithInvocation(TransactionInterceptor.java%3A123)%22%2C%22example-app%22%5D))
 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction([TransactionAspectSupport.java:390](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java%3A390)%22%2C%22example-app%22%5D))
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke([TransactionInterceptor.java:119](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java%3A119)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke([PersistenceExceptionTranslationInterceptor.java:137](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java%3A137)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke([CrudMethodMetadataPostProcessor.java:163](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor%24CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java%3A163)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke([ExposeInvocationInterceptor.java:97](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java%3A97)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:184](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A184)%22%2C%22example-app%22%5D))
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke([JdkDynamicAopProxy.java:218](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java%3A218)%22%2C%22example-app%22%5D))
 at jdk.proxy2/jdk.proxy2.$Proxy137.findAll(Unknown Source)
 at com.example.exampleapp.api.client.ClientRepositoryMediumTest.findAll_RsqlSpecificationIncludingApostraphe_ClientFoundInsteadOfException([ClientRepositoryMediumTest.java:104](command:_java.test.openStackTrace?%5B%22%5Ctat%20com.example.exampleapp.api.client.ClientRepositoryMediumTest.findAll_RsqlSpecificationIncludingApostraphe_ClientFoundInsteadOfException(ClientRepositoryMediumTest.java%3A104)%22%2C%22example-app%22%5D))
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
Caused by: cz.jirutka.rsql.parser.TokenMgrError: Lexical error at line 1, column 17.  Encountered: [EOF] after : "\'s"
 at cz.jirutka.rsql.parser.ParserTokenManager.getNextToken([ParserTokenManager.java:477](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.ParserTokenManager.getNextToken(ParserTokenManager.java%3A477)%22%2C%22example-app%22%5D))
 at cz.jirutka.rsql.parser.Parser.jj_ntk([Parser.java:347](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.Parser.jj_ntk(Parser.java%3A347)%22%2C%22example-app%22%5D))
 at cz.jirutka.rsql.parser.Parser.And([Parser.java:74](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.Parser.And(Parser.java%3A74)%22%2C%22example-app%22%5D))
 at cz.jirutka.rsql.parser.Parser.Or([Parser.java:47](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.Parser.Or(Parser.java%3A47)%22%2C%22example-app%22%5D))
 at cz.jirutka.rsql.parser.Parser.Input([Parser.java:38](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.Parser.Input(Parser.java%3A38)%22%2C%22example-app%22%5D))
 at cz.jirutka.rsql.parser.RSQLParser.parse([RSQLParser.java:120](command:_java.test.openStackTrace?%5B%22%5Ctat%20cz.jirutka.rsql.parser.RSQLParser.parse(RSQLParser.java%3A120)%22%2C%22example-app%22%5D))
 ... 104 moree

**Comment by nstdio** [comment]
I believe this is the issue/question/enhancement for https://github.com/jirutka/rsql-parser. It's the library we use to parse RSQL, and Exception is originated from there, but I'm afraid that project seemed to be abandoned.

**Comment by nstdio** [comment]
@derylspielman Double quotes are missing for argument: `"name=ilike=\"RSQL's\""`

**Comment by derylspielman** [comment]
Nice double quotes does suffice nicely. I guess until we come across an issue where double quotes is one of the values. rsql-parser library has its own escaping rules but I have found them to not work properly.

**Comment by derylspielman** [comment]
On a side note I was getting `java.lang.IllegalStateException: No entity manager bean found in application context at io.github.perplexhub.rsql.RSQLVisitorBase.getManagedType(RSQLVisitorBase.java:185)` in a `@DataJpaTest` within the unit test mentioned. To resolve you need to import the `RSQLJPAAutoConfiguration.class` like below:

```java
@DataJpaTest
@ImportAutoConfiguration(RSQLJPAAutoConfiguration.class)
class ClientRepositoryMediumTest {
```
