### ISSUE TITLE
Issue Trying to Retrieve Nested Entities

### ISSUE THREAD

**Issue by OrbyOSullivan** [perplexhub/rsql-jpa-specification#11]
I'm trying to use [rsql-jpa-specification][1] to expose the data in my entities through a REST api. 

If i pass the following filter string `"sites.id==2"` into my service i get the expected results.  However,
if i try accessing any nested entities i.e. a trunk by id within a site using a filter string `"sites.id==2 and sites.trunks.id==2"` i get the following exception:

message": "Illegal attempt to dereference path source [null.trunks] of basic type; nested exception is java.lang.IllegalStateException: Illegal attempt to dereference path source [null.trunks] of basic type",
    "path": "/api/v1/trunkgroup/filters/sites.id==2%20and%20sites.trunks.id==2"

	
Full stacktrace:	
	
    java.lang.IllegalStateException: Illegal attempt to dereference path source [null.trunks] of basic type
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.illegalDereference(AbstractPathImpl.java:82) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:174) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.findPropertyPath(RSQLJpaPredicateConverter.java:76) ~[rsql-jpa-specification-4.0.12.jar:na]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.visit(RSQLJpaPredicateConverter.java:95) ~[rsql-jpa-specification-4.0.12.jar:na]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.visit(RSQLJpaPredicateConverter.java:30) ~[rsql-jpa-specification-4.0.12.jar:na]
	at cz.jirutka.rsql.parser.ast.ComparisonNode.accept(ComparisonNode.java:70) ~[rsql-parser-2.1.0.jar:2.1.0]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.lambda$visit$0(RSQLJpaPredicateConverter.java:212) ~[rsql-jpa-specification-4.0.12.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.visit(RSQLJpaPredicateConverter.java:212) ~[rsql-jpa-specification-4.0.12.jar:na]
	at io.github.perplexhub.rsql.RSQLJpaPredicateConverter.visit(RSQLJpaPredicateConverter.java:30) ~[rsql-jpa-specification-4.0.12.jar:na]
	at cz.jirutka.rsql.parser.ast.AndNode.accept(AndNode.java:42) ~[rsql-parser-2.1.0.jar:2.1.0]
	at io.github.perplexhub.rsql.RSQLSupport$1.toPredicate(RSQLSupport.java:65) ~[rsql-jpa-specification-4.0.12.jar:na]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.applySpecificationToCriteria(SimpleJpaRepository.java:740) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:671) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.getQuery(SimpleJpaRepository.java:655) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:419) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:359) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:644) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:608) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:144) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$ExposeRepositoryInvocationInterceptor.invoke(CrudMethodMetadataPostProcessor.java:364) ~[spring-data-jpa-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.10.RELEASE.jar:2.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at com.sun.proxy.$Proxy95.findAll(Unknown Source) ~[na:na]
 

    @Data
    @Entity
    @Table(name="trunk_group")
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    public class TrunkGroup implements Serializable {
    	
    	private static final long serialVersionUID = 1L; 
    	
    	@Id
    	@GeneratedValue(strategy=GenerationType.IDENTITY)
    	@Column(name = "_id", updatable = false, nullable = false)
    	private Long id;
    
    	@OneToMany(mappedBy="trunkGroup", cascade={CascadeType.PERSIST, CascadeType.REMOVE},orphanRemoval=true)	
    	private List<Site> sites;
    }

    @Data
    @Entity
    @Table(name="site")
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    public class Site implements Serializable {
    	
    	private static final long serialVersionUID = 1L;
    	
    	@Id
    	@GeneratedValue(strategy=GenerationType.IDENTITY)
    	@Column(name = "_id", updatable = false, nullable = false)
    	private Long id;
    	
    	private String siteId;
    	
    	@ManyToOne
    	@JoinColumn(name="trunkGroup_id", nullable=false)
    	private TrunkGroup trunkGroup;
    			
    	@OneToMany(mappedBy = "site", cascade=CascadeType.PERSIST)
    	private List<Trunk> trunks;
    		
    	@OneToMany(mappedBy = "site", cascade=CascadeType.PERSIST)
    	private List<DDI> ddis;
    	
    }

    @Data
    @Entity
    @Table(name="trunk")
    @NoArgsConstructor
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    public class Trunk implements Serializable {
    	
    	private static final long serialVersionUID = 1L; 
    	
    	@Id
    	@GeneratedValue(strategy=GenerationType.IDENTITY)
    	@Column(name = "_id", updatable = false, nullable = false)
    	private Long id;
    
    	@ManyToOne
    	@JoinColumn(name="site_id", nullable=false)
    	private Site site;
    }

  [1]: https://github.com/perplexhub/rsql-jpa-specification

**Comment by perplexhub** [comment]
Please try using version 4.0.14, thanks.

**Comment by OrbyOSullivan** [comment]
Is 4.0.14 available for Maven?

**Comment by perplexhub** [comment]
https://oss.sonatype.org/#nexus-search;gav~io.github.perplexhub~rsql-jpa-specification

<dependency>
  <groupId>io.github.perplexhub</groupId>
  <artifactId>rsql-jpa-specification</artifactId>
  <version>4.0.14</version>
</dependency>

**Comment by perplexhub** [comment]
https://repo1.maven.org/maven2/io/github/perplexhub/rsql-jpa-specification/
