### ISSUE TITLE
Unexpected value type querying for Long

### ISSUE THREAD

**Issue by jamoros** [perplexhub/rsql-jpa-specification#110]
Greetings! I am using the rsql-jpa-spring-boot-starter with spring boot 3. So far all my queries work with no issues, but now I am trying to do something as simple as

```
query = "id==1";
repository.findAll(RSQLJPASupport.toSpecification(query));
```

And I get the following error:
```
java.lang.AssertionError: Unexpected value type (expected : java.lang.Integer) : 1 (java.lang.String)
	at org.hibernate.sql.exec.internal.JdbcParameterBindingImpl.<init>(JdbcParameterBindingImpl.java:23)
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.createAndAddBinding(JdbcParameterBindings.java:97)
	at org.hibernate.type.BasicType.forEachDisassembledJdbcValue(BasicType.java:135)
	at org.hibernate.metamodel.mapping.Bindable.forEachJdbcValue(Bindable.java:197)
```
I've read all the docs in the read me and tried other ways such as >1=;<=1 but anything I do with a number for an ID I get the above error. 

The ID in my class is the following

```
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
```
What can I possibly be doing wrong, is there anything I need to add so that it accepts Longs in the query?

Thank you!

**Comment by perplexhub** [comment]
Not sure, the exception was raised in hibernate. You may try to print out the generated SQL and parameters to check further.

**Comment by jamoros** [comment]
I think I am fine with removing the generic for the concrete Long for the ID, but I was wondering if there was something to fix it. This is the logging with the generated sql and the exception:

```
Hibernate: 
    select
        t1_0.id,
        t1_0.instance_id,
        t1_0.version 
    from
        instance t1_0 
    where
        t1_0.id=?

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.635 s <<< FAILURE! -  Time elapsed: 0.769 s  <<< 
FAILURE!
java.lang.AssertionError: Unexpected value type (expected : java.lang.Long) : 1 (java.lang.String)
	at org.hibernate.sql.exec.internal.JdbcParameterBindingImpl.<init>(JdbcParameterBindingImpl.java:23)
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.createAndAddBinding(JdbcParameterBindings.java:97)
	at org.hibernate.type.BasicType.forEachDisassembledJdbcValue(BasicType.java:135)
	at org.hibernate.metamodel.mapping.Bindable.forEachJdbcValue(Bindable.java:197)
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:78)
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:69)
	at org.hibernate.query.sqm.internal.SqmUtil.createValueBindings(SqmUtil.java:409)
	at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:338)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:358)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:268)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:244)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:518)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:367)
	at org.hibernate.query.Query.getResultList(Query.java:119)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll(SimpleJpaRepository.java:440)
```

Thanks!

**Comment by perplexhub** [comment]
Do you see this message in the debug log?
convert(source:1,targetType:Class java.lang.String)

**Comment by jamoros** [comment]
It's Object instead of String, here is the log (with some previous lines)

```
i.github.perplexhub.rsql.RSQLJPASupport  : toSpecification(Instance.id==1,distinct:false,propertyPathMapper:null,customPredicates:0,joinHints:null,propertyWhitelist:null,propertyBlacklist:null)
i.g.p.rsql.RSQLJPAPredicateConverter     : visit(node:Instance.id=='1',root:com.workflow.InstanceVariable)
i.g.perplexhub.rsql.RSQLVisitorBase      : Found managed type [class com.workflow.InstanceVariable] in EntityManager [jpaSharedEM_AWC_entityManagerFactory]
i.g.perplexhub.rsql.RSQLVisitorBase      : Found managed type [class com.workflow.Instance] in EntityManager [jpaSharedEM_AWC_entityManagerFactory]
i.g.p.rsql.RSQLJPAPredicateConverter     : Create property path for type [com.workflow.Instance] property [Instance]
i.g.p.rsql.RSQLJPAPredicateConverter     : Create property path for type [com.workflow.Instance] property [id]
i.g.perplexhub.rsql.RSQLVisitorBase      : accessControl(type:class com.workflow.Instance,name:id)
i.g.perplexhub.rsql.RSQLVisitorBase      : convert(source:1,targetType:class java.lang.Object)
o.h.q.sqm.sql.BaseSqmToSqlAstConverter   : Determining mapping-model type for SqmParameter : org.hibernate.query.sqm.tree.expression.SqmJpaCriteriaParameterWrapper@5a0b550a

Time elapsed: 0.698 s  <<< FAILURE!
java.lang.AssertionError: Unexpected value type (expected : java.lang.Long) : 1 (java.lang.String)
```

**Comment by perplexhub** [comment]
It looks like attribute.getJavaType() in [RSQLJPAPredicateConverter](https://github.com/perplexhub/rsql-jpa-specification/blob/b8be22aa4db1f1940890e3673a543418c5977cdd/rsql-jpa/src/main/java/io/github/perplexhub/rsql/RSQLJPAPredicateConverter.java#L197) returns Object instead of Long for your entity class.

**Comment by jamoros** [comment]
You're correct, that it's returning Object instead of Long. I put a breakpoint however I cannot find any reasons why this would be. Is there any additional info I can provide from the breakpoint? I attached a screenshot of the attribute with some of it's values.

![image](https://github.com/perplexhub/rsql-jpa-specification/assets/1895328/8c0ae63d-2c9c-4f10-b367-5d86307304c6)
