### ISSUE TITLE
Support Spring Boot 3

### ISSUE THREAD

**Issue by manosbatsis** [perplexhub/rsql-jpa-specification#62]
See [this section](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0#check-if-third-party-projects-have-jakarta-ee-9-compatible-releases) in [Preparing for Spring Boot 3.0](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0).

Main issue should be the use of Jakarta EE 9 APIs (jakarta.*) instead of EE 8 (javax.*), e.g. `javax.persistence.EntityManager` should be `jakarta.persistence.EntityManager`. 

Tried Spring Boot 3.0.0-M3 with the current release and it fails to launch with

```
java.lang.AbstractMethodError: Receiver class io.github.perplexhub.rsql.RSQLJPASupport$1 does not define or inherit an implementation of the resolved method &#39;abstract jakarta.persistence.criteria.Predicate toPredicate(jakarta.persistence.criteria.Root, jakarta.persistence.criteria.CriteriaQuery, jakarta.persistence.criteria.CriteriaBuilder)&#39; of interface org.springframework.data.jpa.domain.Specification.
```

**Comment by perplexhub** [comment]
V6.0.2

**Comment by luisalves00** [comment]
I'm getting:

```
Caused by: java.lang.IllegalStateException: No entity manager bean found in application context
	at io.github.perplexhub.rsql.RSQLVisitorBase.getManagedType(RSQLVisitorBase.java:186) ~[rsql-common-6.0.2.jar:?]
	at io.github.perplexhub.rsql.RSQLJPAPredicateConverter.findPropertyPath(RSQLJPAPredicateConverter.java:61) ~[rsql-jpa-6.0.2.jar:?]
	at io.github.perplexhub.rsql.RSQLJPAPredicateConverter.visit(RSQLJPAPredicateConverter.java:188) ~[rsql-jpa-6.0.2.jar:?]
	at io.github.perplexhub.rsql.RSQLJPAPredicateConverter.visit(RSQLJPAPredicateConverter.java:25) ~[rsql-jpa-6.0.2.jar:?]
```

Do I need to do some extra configuration?

**Comment by perplexhub** [comment]
Are you using the starter dependency?

**Comment by perplexhub** [comment]
Does this help?
https://github.com/perplexhub/rsql-jpa-specification/blob/master/rsql-jpa/src/test/java/io/github/perplexhub/rsql/Application.java

**Comment by luisalves00** [comment]
wow...that's was fast

![image](https://user-images.githubusercontent.com/3064521/210847301-27a1ccf9-6900-4b9b-9ed6-e83d7dd74dff.png)

I think is the auto configuration that is not kicking in.

on spring boot 3 you need to define it like:

![image](https://user-images.githubusercontent.com/3064521/210847716-852133ea-6fa1-4fc6-922c-6e17fd3dbce0.png)

so a filie like this:
META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

and the file content is just:
io.github.perplexhub.rsql.RSQLJPAAutoConfiguration

**Comment by perplexhub** [comment]
Thanks for pointing out. Would you mind to create a PR to fix it? Thanks.

**Comment by luisalves00** [comment]
Thanks. You're proposal will work I guess...as I said is only the auto configuration that isn't working.
When you find time to update for the spring boot 3 auto configuration style, let me know.

**Comment by luisalves00** [comment]
I can try to create the PR tomorrow.

**Comment by alierdogan7** [comment]
> Does it help? https://github.com/perplexhub/rsql-jpa-specification/blob/master/rsql-jpa/src/test/java/io/github/perplexhub/rsql/Application.java

I ran into the same issue which caused `No entity manager bean found in application context` and the solution was adding `@EnableJpaRepositories(basePackages = { "io.github.perplexhub.rsql" }})` annotation as shown in `Application.java`. Thanks for this great work! @perplexhub 

By the way, this configuration was not mentioned in [README ](https://github.com/perplexhub/rsql-jpa-specification/blob/master/README.md) file. Could you add this requirement for others to be aware of that config? @perplexhub

**Comment by perplexhub** [comment]
Updated. Thanks.
